export const RECEIVE_POKEMON_SUCCESS = 'RECEIVE_POKEMON_SUCCESS';
export const RECEIVE_POKEMON_FAIL = 'RECEIVE_POKEMON_FAIL';
export const FETCHING_REQUEST = 'FETCHING_REQUEST';
export const ADD_POKEMON = 'ADD_POKEMON';
export const REMOVE_POKEMON = 'REMOVE_POKEMON';
export const UPDATE_POKEMON_INFO = 'UPDATE_POKEMON_INFO';
